;<?php die('');?>
isWindows=on
enableAllModules=
disableInstallers=
chmodDir=509
chmodFile=436
forceHTTPSPort=
forceHTTPPort=
domainName=localhost
timeZone="Europe/Paris"
httpVersion=
theme=default
charset=UTF-8
fallbackLocale=en_US
locale=en_US
[availableLocales]
0=cs_CZ
1=de_DE
2=el_GR
3=en_US
4=es_ES
5=eu_ES
6=fi_FI
7=fr_FR
8=gl_ES
9=hu_HU
10=it_IT
11=ja_JP
12=nl_NL
13=no_NO
14=pl_PL
15=pt_BR
16=pt_PT
17=ro_RO
18=ru_RU
19=sl_SI
20=sv_SE
21=sk_SK
22=uk_UA
[modules]
jelix.enabled=on
jelix.path="lib:jelix/core-modules/jelix"
jacldb.enabled=
jelix.installparam[]=copy
jacl.enabled=
jpref.enabled=
jsoap.enabled=
junittests.enabled=
jpref_admin.enabled=
jacl2.enabled=on
jacl2db.enabled=on
jacl2db.installparam=defaultuser
jauth.enabled=
jauthdb.enabled=
jcommunity.enabled=on
jcommunity.installparam[]=on
jcommunity.installparam[]=
jcommunity.installparam[]="lizmap~defaultusers.json"
jcommunity.installparam[]="[index,admin]"
admin.enabled=on
dataviz.enabled=on
filter.enabled=on
action.enabled=on
dynamicLayers.enabled=on
lizmap.enabled=on
proj4php.enabled=on
view.enabled=on
jacl2db_admin.enabled=on
jauthdb_admin.enabled=on
master_admin.enabled=on
multiauth.installparam[]=on
multiauth.installparam[]="[index,admin]"
ldapdao.installparam[]=on
ldapdao.path="app:vendor/jelix/ldapdao-module/ldapdao"
saml.installparam[]=on
saml.installparam[]=admin
ldapdao.enabled=
ldapdao.dbprofile=default
jelix.dbprofile=default
jcommunity.dbprofile=default
jmessenger.enabled=
jmessenger.dbprofile=default
jacl.dbprofile=default
jacl2.dbprofile=default
jacl2db.dbprofile=default
jacldb.dbprofile=default
jauth.dbprofile=default
jauthdb.dbprofile=default
jpref.dbprofile=default
jacl2db_admin.dbprofile=default
jauthdb_admin.dbprofile=default
jpref_admin.dbprofile=default
master_admin.dbprofile=default
action.dbprofile=default
admin.dbprofile=default
dataviz.dbprofile=default
dynamicLayers.dbprofile=default
filter.dbprofile=default
lizmap.dbprofile=default
proj4php.dbprofile=default
view.dbprofile=default
[coordplugins]
autolocale=1
auth="app/system/index/auth.coord.ini.php"
jacl2=1
lizmap="var/config/lizmapConfig.ini.php"
[tplplugins]
defaultJformsBuilder=html
defaultJformsErrorDecorator=
[responses]
html=myHtmlResponse
htmlerror=jResponseHtmlError
basichtml=jResponseBasicHtml
redirect=jResponseRedirect
redirectUrl=jResponseRedirectUrl
binary=jResponseBinary
streamed=jResponseStreamed
text=jResponseText
cmdline=jResponseCmdline
jsonrpc=jResponseJsonrpc
json=jResponseJson
xmlrpc=jResponseXmlrpc
xml=jResponseXml
zip=jResponseZip
css=jResponseCss
htmlfragment=jResponseHtmlFragment
htmlauth=jResponseHtml
formjq=jResponseFormJQJson
htmlmap=myHtmlMapResponse
htmlsimple=simpleHtmlResponse
html.path="C:\webserver\www\lizmap36\lizmap/app/responses/myHtmlResponse.class.php"
htmlerror.path="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix/core/response/jResponseHtmlError.class.php"
basichtml.path="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix/core/response/jResponseBasicHtml.class.php"
redirect.path="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix/core/response/jResponseRedirect.class.php"
redirectUrl.path="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix/core/response/jResponseRedirectUrl.class.php"
binary.path="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix/core/response/jResponseBinary.class.php"
streamed.path="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix/core/response/jResponseStreamed.class.php"
text.path="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix/core/response/jResponseText.class.php"
cmdline.path="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix/core/response/jResponseCmdline.class.php"
jsonrpc.path="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix/core/response/jResponseJsonrpc.class.php"
json.path="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix/core/response/jResponseJson.class.php"
xmlrpc.path="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix/core/response/jResponseXmlrpc.class.php"
xml.path="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix/core/response/jResponseXml.class.php"
zip.path="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix/core/response/jResponseZip.class.php"
css.path="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix/core/response/jResponseCss.class.php"
htmlfragment.path="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix/core/response/jResponseHtmlFragment.class.php"
htmlauth.path="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix/core/response/jResponseHtml.class.php"
formjq.path="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix/core/response/jResponseFormJQJson.class.php"
htmlmap.path="C:\webserver\www\lizmap36\lizmap/app/responses/myHtmlMapResponse.class.php"
htmlsimple.path="C:\webserver\www\lizmap36\lizmap/app/responses/simpleHtmlResponse.class.php"
[_coreResponses]
html=jResponseHtml
htmlerror=jResponseHtmlError
basichtml=jResponseBasicHtml
redirect=jResponseRedirect
redirectUrl=jResponseRedirectUrl
binary=jResponseBinary
streamed=jResponseStreamed
text=jResponseText
cmdline=jResponseCmdline
jsonrpc=jResponseJsonrpc
json=jResponseJson
xmlrpc=jResponseXmlrpc
xml=jResponseXml
zip=jResponseZip
css=jResponseCss
htmlfragment=jResponseHtmlFragment
htmlauth=jResponseHtml
formjq=jResponseFormJQJson
html.path="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix/core/response/jResponseHtml.class.php"
htmlerror.path="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix/core/response/jResponseHtmlError.class.php"
basichtml.path="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix/core/response/jResponseBasicHtml.class.php"
redirect.path="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix/core/response/jResponseRedirect.class.php"
redirectUrl.path="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix/core/response/jResponseRedirectUrl.class.php"
binary.path="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix/core/response/jResponseBinary.class.php"
streamed.path="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix/core/response/jResponseStreamed.class.php"
text.path="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix/core/response/jResponseText.class.php"
cmdline.path="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix/core/response/jResponseCmdline.class.php"
jsonrpc.path="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix/core/response/jResponseJsonrpc.class.php"
json.path="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix/core/response/jResponseJson.class.php"
xmlrpc.path="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix/core/response/jResponseXmlrpc.class.php"
xml.path="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix/core/response/jResponseXml.class.php"
zip.path="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix/core/response/jResponseZip.class.php"
css.path="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix/core/response/jResponseCss.class.php"
htmlfragment.path="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix/core/response/jResponseHtmlFragment.class.php"
htmlauth.path="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix/core/response/jResponseHtml.class.php"
formjq.path="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix/core/response/jResponseFormJQJson.class.php"
[jResponseHtml]
plugins=
minifyCSS=
minifyJS=on
minifyExcludeCSS=
minifyExcludeJS="jelix/ckeditor5/ckeditor.js"
minifyEntryPoint=minify.php
[debugbar]
plugins="sqllog,sessiondata,defaultlog"
defaultPosition=right
errors_openon=error
[error_handling]
messageLogFormat="%date%\t[%code%]\t%msg%\t%file%\t%line%\n"
errorMessage="An error occured. Sorry for the inconvenience."
sensitiveParameters[]=password
sensitiveParameters[]=passwd
sensitiveParameters[]=pwd
[compilation]
sourceFileResolutionInCache=
checkCacheFiletime=on
force=
[urlengine]
enableParser=on
multiview=
scriptNameServerVariable=SCRIPT_NAME
pathInfoInQueryParameter=
basePath="/lizmap36/lizmap/www/"
backendBasePath=
forceProxyProtocol=
checkHttpsOnParsing=on
jelixWWWPath="/lizmap36/lizmap/www/assets/jelix/"
jqueryPath="/lizmap36/lizmap/www/assets/jelix/jquery/"
notFoundAct="jelix~error:notfound"
significantFile=urls.xml
localSignificantFile=localurls.xml
urlScript="/lizmap36/lizmap/www/index.php"
urlScriptPath="/lizmap36/lizmap/www/"
urlScriptName=index.php
urlScriptId=index
urlScriptIdenc=index
documentRoot="C:/webserver/www/"
assetsRevision=231007075320
assetsRevisionParameter=_r
assetsRevQueryUrl="_r=231007075320"
notfoundAct="jelix~error:notfound"
[logger]
_all=
default=file
error=file
warning=file
notice=file
deprecated=
strict=file
debug=
sql=
soap=
metric=syslog
auth=
lizmapadmin=file
[fileLogger]
default=messages.log
error=errors.log
warning=errors.log
notice=errors.log
deprecated=errors.log
strict=errors.log
debug=debug.log
auth=messages.log
lizmapadmin=lizmap-admin.log
[memorylogger]
default=20
error=10
warning=10
notice=10
deprecated=10
strict=10
debug=20
sql=20
soap=20
[mailLogger]
email="root@localhost"
emailHeaders="Content-Type: text/plain; charset=UTF-8\nFrom: webmaster@yoursite.com\nX-Mailer: Jelix\nX-Priority: 1 (Highest)\n"
[syslogLogger]
facility=LOG_LOCAL7
ident="php-%sapi%-%domain%[%pid%]"
[stderrLogger]
[stdoutLogger]
[mailer]
webmasterEmail=
webmasterName=
replyTo=
returnPath=
mailerType=mail
hostname=
sendmailPath="/usr/sbin/sendmail"
filesDir="mails/"
smtpProfile=mailer
smtpHost=localhost
smtpPort=25
smtpSecure=
smtpHelo=
smtpAuth=
smtpUsername=
smtpPassword=
smtpTimeout=10
copyToFiles=
debugModeEnabled=
debugReceiversType=1
debugReceivers=
debugReceiversWhiteList=
debugFrom=
debugFromName=
debugSubjectPrefix=
debugBodyIntroduction=
debugSmtpLevel=0
[acl]
driver=
[sessions]
start=1
shared_session=
cookieSecure=
cookieHttpOnly=on
cookieLifetime=0
cookieSameSite=
name=
storage=
loadClasses=
[forms]
controls.datetime.input=menulists
controls.time.input=menulists
controls.datetime.months.labels=numbers
datepicker=default
datetimepicker=default
timepicker=
captcha=simple
captcha.simple.validator="\jelix\forms\Captcha\SimpleCaptchaValidator"
captcha.simple.widgettype=captcha
captcha.recaptcha.validator="\jelix\forms\Captcha\ReCaptchaValidator"
captcha.recaptcha.widgettype=recaptcha
flagPrepareObjectFromControlsContactArrayValues=0
[jforms_builder_html]
[htmleditors]
default.engine.name=ckeditor
ckdefault.engine.name=ckeditor
ckfull.engine.name=ckeditor
ckbasic.engine.name=ckeditor
ckfullandmedia.engine.name=ckeditor
[wikieditors]
default.engine.name=wr3
default.wiki.rules=wr3_to_xhtml
[webassets]
useCollection=common
[webassets_common]
jquery.js[]="assets/js/jquery/jquery-3.5.1.min.js"
jquery.js[]="assets/js/jquery/jquery-migrate-3.3.1.min.js"
jquery_ui.js="$jelix/jquery/ui/jquery-ui.min.js"
jquery_ui.css[]="$jelix/jquery/ui/jquery-ui.min.css"
jquery_ui.require=jquery
jforms_html.js[]="$jelix/js/jforms_jquery.js"
jforms_html.css="$jelix/design/jform.css"
jforms_html.require=jquery
jforms_html_light.js="$jelix/js/jforms_light.js"
jforms_html_light.css="$jelix/design/jform.css"
jforms_datepicker_default.css=
jforms_datepicker_default.js[]="$jelix/jquery/ui/i18n/datepicker-$lang.js"
jforms_datepicker_default.js[]="$jelix/js/jforms/datepickers/default/ui.$lang.js"
jforms_datepicker_default.js[]="$jelix/js/jforms/datepickers/default/init.js"
jforms_datepicker_default.require=jquery_ui
jforms_datetimepicker_default.require=jforms_datepicker_default
jforms_datetimepicker_default.js[]="$jelix/js/jforms/datetimepickers/default/init.js"
jforms_datetimepicker_default.js[]="$jelix/jquery/jquery-ui-timepicker-addon.js"
jforms_datetimepicker_default.css="$jelix/jquery/jquery-ui-timepicker-addon.css"
jforms_htmleditor_default.js[]="$jelix/ckeditor5/ckeditor.js"
jforms_htmleditor_default.js[]="$jelix/ckeditor5/translations/$lang.js"
jforms_htmleditor_default.js[]="assets/js/ckeditor5/ckeditor_lizmap.js"
jforms_htmleditor_ckdefault.js[]="$jelix/ckeditor5/ckeditor.js"
jforms_htmleditor_ckdefault.js[]="$jelix/ckeditor5/translations/$lang.js"
jforms_htmleditor_ckdefault.js[]="assets/js/ckeditor5/ckeditor_lizmap.js"
jforms_htmleditor_ckfull.js[]="$jelix/ckeditor5/ckeditor.js"
jforms_htmleditor_ckfull.js[]="$jelix/ckeditor5/translations/$lang.js"
jforms_htmleditor_ckfull.js[]="$jelix/js/jforms/htmleditors/ckeditor_ckfull.js"
jforms_htmleditor_ckbasic.js[]="$jelix/ckeditor5/ckeditor.js"
jforms_htmleditor_ckbasic.js[]="$jelix/ckeditor5/translations/$lang.js"
jforms_htmleditor_ckbasic.js[]="$jelix/js/jforms/htmleditors/ckeditor_ckbasic.js"
jforms_wikieditor_default.js[]="$jelix/markitup/jquery.markitup.js"
jforms_wikieditor_default.js[]="$jelix/markitup/sets/wr3/$locale.js"
jforms_wikieditor_default.css[]="$jelix/markitup/skins/simple/style.css"
jforms_wikieditor_default.css[]="$jelix/markitup/sets/wr3/style.css"
jforms_wikieditor_default.require=jquery
jforms_imageupload.js[]="$jelix/js/cropper.min.js"
jforms_imageupload.js[]="$jelix/js/jforms/choice.js"
jforms_imageupload.js[]="$jelix/js/jforms/imageSelector.js"
jforms_imageupload.css[]="$jelix/js/cropper.min.css"
jforms_imageupload.require=jquery_ui
jforms_autocomplete.js[]="$jelix/js/jforms/jAutocomplete.jqueryui.js"
jforms_autocomplete.require=jquery_ui
jforms_autocompleteajax.js[]="$jelix/js/jforms/jAutocompleteAjax.jqueryui.js"
jforms_autocompleteajax.require=jquery_ui
datatables.js[]="assets/js/jquery.dataTables.min.js"
datatables.js[]="assets/js/dataTables.bootstrap.min.js"
datatables.js[]="$jelix/datatables/i18n/$locale.js"
datatables.css[]="assets/css/jquery.dataTables.min.css"
datatables.css[]="assets/css/dataTables.bootstrap.min.css"
jforms_htmleditor_ckfullandmedia.js[]="$jelix/ckeditor5/ckeditor.js"
jforms_htmleditor_ckfullandmedia.js[]="$jelix/ckeditor5/translations/$lang.js"
jforms_htmleditor_ckfullandmedia.js[]="assets/js/ckeditor5/ckeditor_ckfullandmedia.js"
bootstrap.require=jquery
bootstrap.js[]="assets/js/bootstrap.min.js"
bootstrap.css[]="assets/css/bootstrap.min.css"
bootstrap.css[]="assets/css/bootstrap-responsive.min.css"
datatables.require=bootstrap
map.require=bootstrap
map.js[]="assets/js/OpenLayers-2.13/OpenLayers.js"
map.js[]="assets/js/Proj4js/proj4js.min.js"
map.js[]="assets/js/jquery.combobox.js"
map.js[]="assets/js/TreeTable/javascripts/jquery.treeTable.js"
map.js[]="assets/js/map.js"
map.js[]="assets/js/lizmap.js"
map.css[]="assets/js/TreeTable/stylesheets/jquery.treeTable.css"
map.css[]="assets/js/OpenLayers-2.13/theme/default/style.css"
map.css[]="assets/css/ol.css"
map.css[]="assets/css/main.css"
map.css[]="assets/css/map.css"
map.css[]="assets/css/media.css"
maptheme.css[]="$theme/css/main.css"
maptheme.css[]="$theme/css/map.css"
maptheme.css[]="$theme/css/media.css"
normal.css[]="assets/css/main.css"
normal.css[]="assets/css/view.css"
normal.css[]="assets/css/media.css"
view.js[]="assets/js/view.js"
embed.css[]="assets/css/embed.css"
embed.css[]="$theme/css/embed.css"
jauthdb_admin.js[]="$jelix/js/authdb_admin.js"
jauthdb_admin.require[]=jquery_ui
jacl2_admin.css[]="$jelix/design/jacl2.css"
jacl2_admin.css[]="$jelix/design/records_list.css"
jacl2_admin.js[]="$jelix/js/jacl2db_admin.js"
jacl2_admin.require[]=jquery_ui
[zones]
disableCache=
[classbindings]
[imagemodifier]
src_url=
src_path=
cache_url=
cache_path=
[rootUrls]
jelix.cache="cache/"
[langToLocale]
locale[]=cs_CZ
locale[]=de_DE
locale[]=el_GR
locale[]=en_US
locale[]=es_ES
locale[]=eu_ES
locale[]=fi_FI
locale[]=fr_FR
locale[]=gl_ES
locale[]=hu_HU
locale[]=it_IT
locale[]=ja_JP
locale[]=nl_NL
locale[]=no_NO
locale[]=pl_PL
locale[]=pt_BR
locale[]=ro_RO
locale[]=ru_RU
locale[]=sl_SI
locale[]=sv_SE
locale[]=sk_SK
locale[]=uk_UA
[disabledListeners]
[mimeTypes]
[coordplugin_auth]
persistant_encryption_key=def0000017dc3257d2a20d352bbe8d74ca083e2bab1797a15c764f4ce9c2919104df4ccd310f649e8cebc4d86e65e57dff4dd6f00494226d78ff690878c59df00c66f383
[recaptcha]
sitekey=
secret=
theme=
type=
size=
tabindex=
[minimumRequiredVersion]
qgisServer=3.10
lizmapServerPlugin=2.8.1
lizmapWebClientTargetVersion=30300
[lizmap]
mapCSPHeader=
adminCSPHeader=
setAdminContactEmailAsReplyTo=
[coordplugin_autolocale]
enableUrlDetection=on
urlParamNameLanguage=lang
useDefaultLanguageBrowser=on
[jacl2]
on_error=2
error_message="jelix~errors.acl.action.right.needed"
on_error_action="jcommunity~login:index"
[acl2]
hiddenRights=
hideRights=
driver=db
authAdapterClass=jAcl2JAuthAdapter
[jcommunity]
loginResponse=htmlauth
registrationEnabled=
resetPasswordEnabled=on
resetAdminPasswordEnabled=on
verifyNickname=
useJAuthDbAdminRights=on
[saml:sp]
daoPropertiesForMapping="login,email,firstname,lastname,phonenumber"
[pgsqlSchemaTimeout]
cadastre=31
adresse=32
openads=33
[_allBasePath]
0="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jcommunity-module\modules"
1="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix-modules"
2="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix-admin-modules"
3="C:\webserver\www\lizmap36\lizmap\modules"
4="C:\webserver\www\lizmap36\lizmap\lizmap-modules"
5="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix-plugins\cache/"
6="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix-plugins\kvdb/"
7="C:\webserver\www\lizmap36\lizmap\plugins\auth/"
8="C:\webserver\www\lizmap36\lizmap\plugins\configcompiler/"
9="C:\webserver\www\lizmap36\lizmap\plugins\coord/"
10="C:\webserver\www\lizmap36\lizmap\plugins\db/"
11="C:\webserver\www\lizmap36\lizmap\plugins\formbuilder/"
12="C:\webserver\www\lizmap36\lizmap\plugins\formwidget/"
13="C:\webserver\www\lizmap36\lizmap\plugins\tpl/"
14="C:\webserver\www\lizmap36\lizmap/vendor/jelix/ldapdao-module/ldapdao\plugins\auth/"
15="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix-modules\jacl\plugins\coord/"
16="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix-modules\jacl\plugins\tpl/"
17="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix-modules\jacl2\plugins\coord/"
18="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix-modules\jacl2\plugins\tpl/"
19="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix-modules\jacl2db\plugins\acl2/"
20="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix-modules\jacldb\plugins\acl/"
[_modulesPathList]
jelix="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib/jelix/core-modules/jelix\"
jcommunity="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jcommunity-module\modules\jcommunity\"
jacl2="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix-modules\jacl2\"
jacl2db="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix-modules\jacl2db\"
jacl2db_admin="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix-admin-modules\jacl2db_admin\"
jauthdb_admin="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix-admin-modules\jauthdb_admin\"
master_admin="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix-admin-modules\master_admin\"
action="C:\webserver\www\lizmap36\lizmap\modules\action\"
admin="C:\webserver\www\lizmap36\lizmap\modules\admin\"
dataviz="C:\webserver\www\lizmap36\lizmap\modules\dataviz\"
dynamicLayers="C:\webserver\www\lizmap36\lizmap\modules\dynamicLayers\"
filter="C:\webserver\www\lizmap36\lizmap\modules\filter\"
lizmap="C:\webserver\www\lizmap36\lizmap\modules\lizmap\"
proj4php="C:\webserver\www\lizmap36\lizmap\modules\proj4php\"
view="C:\webserver\www\lizmap36\lizmap\modules\view\"
[_pluginsPathList_auth]
class="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\auth/class/"
db="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\auth/db/"
ldap="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\auth/ldap/"
ldapdao="C:\webserver\www\lizmap36\lizmap/vendor/jelix/ldapdao-module/ldapdao\plugins\auth/ldapdao/"
[_pluginsPathList_cache]
db="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\cache/db/"
memcache="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\cache/memcache/"
redis_ext="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\cache/redis_ext/"
file="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix-plugins\cache/file/"
[_pluginsPathList_configcompiler]
assetsrevision="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\configcompiler/assetsrevision/"
debugbar="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\configcompiler/debugbar/"
locales="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\configcompiler/locales/"
nsautoloader="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\configcompiler/nsautoloader/"
responses="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\configcompiler/responses/"
session="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\configcompiler/session/"
webassets="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\configcompiler/webassets/"
lizmapconfig="C:\webserver\www\lizmap36\lizmap\plugins\configcompiler/lizmapconfig/"
[_pluginsPathList_coord]
auth="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\coord/auth/"
autolocale="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\coord/autolocale/"
history="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\coord/history/"
traceexec="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\coord/traceexec/"
lizmap="C:\webserver\www\lizmap36\lizmap\plugins\coord/lizmap/"
jacl="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix-modules\jacl\plugins\coord/jacl/"
jacl2="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix-modules\jacl2\plugins\coord/jacl2/"
[_pluginsPathList_daobuilder]
mssql="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\daobuilder/mssql/"
mysql="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\daobuilder/mysql/"
oci="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\daobuilder/oci/"
pgsql="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\daobuilder/pgsql/"
sqlite="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\daobuilder/sqlite/"
sqlsrv="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\daobuilder/sqlsrv/"
[_pluginsPathList_db]
mssql="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\db/mssql/"
mysqli="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\db/mysqli/"
oci="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\db/oci/"
pgsql="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\db/pgsql/"
sqlite3="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\db/sqlite3/"
sqlsrv="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\db/sqlsrv/"
[_pluginsPathList_debugbar]
defaultlog="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\debugbar/defaultlog/"
sessiondata="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\debugbar/sessiondata/"
soaplog="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\debugbar/soaplog/"
sqllog="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\debugbar/sqllog/"
[_pluginsPathList_formbuilder]
html="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\formbuilder/html/"
htmlbootstrap="C:\webserver\www\lizmap36\lizmap\plugins\formbuilder/htmlbootstrap/"
[_pluginsPathList_formwidget]
autocompleteajax_html="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\formwidget/autocompleteajax_html/"
autocomplete_html="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\formwidget/autocomplete_html/"
button_html="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\formwidget/button_html/"
captcha_html="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\formwidget/captcha_html/"
checkboxes_html="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\formwidget/checkboxes_html/"
checkbox_html="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\formwidget/checkbox_html/"
choice_html="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\formwidget/choice_html/"
color_html="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\formwidget/color_html/"
datetime_html="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\formwidget/datetime_html/"
date_html="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\formwidget/date_html/"
group_html="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\formwidget/group_html/"
html="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\formwidget/html/"
htmleditor_html="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\formwidget/htmleditor_html/"
imageupload_html="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\formwidget/imageupload_html/"
input_html="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\formwidget/input_html/"
listbox_html="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\formwidget/listbox_html/"
menulist_html="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\formwidget/menulist_html/"
output_html="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\formwidget/output_html/"
passwordeditor_html="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\formwidget/passwordeditor_html/"
password_html="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\formwidget/password_html/"
radiobuttons_html="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\formwidget/radiobuttons_html/"
recaptcha_html="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\formwidget/recaptcha_html/"
reset_html="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\formwidget/reset_html/"
secretconfirm_html="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\formwidget/secretconfirm_html/"
secret_html="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\formwidget/secret_html/"
submit_html="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\formwidget/submit_html/"
textarea_html="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\formwidget/textarea_html/"
time_html="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\formwidget/time_html/"
upload2_html="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\formwidget/upload2_html/"
upload_html="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\formwidget/upload_html/"
wikieditor_html="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\formwidget/wikieditor_html/"
autocompleteajax_htmlbootstrap="C:\webserver\www\lizmap36\lizmap\plugins\formwidget/autocompleteajax_htmlbootstrap/"
autocomplete_htmlbootstrap="C:\webserver\www\lizmap36\lizmap\plugins\formwidget/autocomplete_htmlbootstrap/"
button_htmlbootstrap="C:\webserver\www\lizmap36\lizmap\plugins\formwidget/button_htmlbootstrap/"
captcha_htmlbootstrap="C:\webserver\www\lizmap36\lizmap\plugins\formwidget/captcha_htmlbootstrap/"
checkboxes_htmlbootstrap="C:\webserver\www\lizmap36\lizmap\plugins\formwidget/checkboxes_htmlbootstrap/"
checkbox_htmlbootstrap="C:\webserver\www\lizmap36\lizmap\plugins\formwidget/checkbox_htmlbootstrap/"
choice_htmlbootstrap="C:\webserver\www\lizmap36\lizmap\plugins\formwidget/choice_htmlbootstrap/"
color_htmlbootstrap="C:\webserver\www\lizmap36\lizmap\plugins\formwidget/color_htmlbootstrap/"
datetime_htmlbootstrap="C:\webserver\www\lizmap36\lizmap\plugins\formwidget/datetime_htmlbootstrap/"
date_htmlbootstrap="C:\webserver\www\lizmap36\lizmap\plugins\formwidget/date_htmlbootstrap/"
group_htmlbootstrap="C:\webserver\www\lizmap36\lizmap\plugins\formwidget/group_htmlbootstrap/"
htmlbootstrap="C:\webserver\www\lizmap36\lizmap\plugins\formwidget/htmlbootstrap/"
htmleditor_htmlbootstrap="C:\webserver\www\lizmap36\lizmap\plugins\formwidget/htmleditor_htmlbootstrap/"
imageupload_htmlbootstrap="C:\webserver\www\lizmap36\lizmap\plugins\formwidget/imageupload_htmlbootstrap/"
input_htmlbootstrap="C:\webserver\www\lizmap36\lizmap\plugins\formwidget/input_htmlbootstrap/"
listbox_htmlbootstrap="C:\webserver\www\lizmap36\lizmap\plugins\formwidget/listbox_htmlbootstrap/"
menulist_htmlbootstrap="C:\webserver\www\lizmap36\lizmap\plugins\formwidget/menulist_htmlbootstrap/"
output_htmlbootstrap="C:\webserver\www\lizmap36\lizmap\plugins\formwidget/output_htmlbootstrap/"
radiobuttons_htmlbootstrap="C:\webserver\www\lizmap36\lizmap\plugins\formwidget/radiobuttons_htmlbootstrap/"
recaptcha_htmlbootstrap="C:\webserver\www\lizmap36\lizmap\plugins\formwidget/recaptcha_htmlbootstrap/"
reset_htmlbootstrap="C:\webserver\www\lizmap36\lizmap\plugins\formwidget/reset_htmlbootstrap/"
secretconfirm_htmlbootstrap="C:\webserver\www\lizmap36\lizmap\plugins\formwidget/secretconfirm_htmlbootstrap/"
secret_htmlbootstrap="C:\webserver\www\lizmap36\lizmap\plugins\formwidget/secret_htmlbootstrap/"
submit_htmlbootstrap="C:\webserver\www\lizmap36\lizmap\plugins\formwidget/submit_htmlbootstrap/"
textarea_htmlbootstrap="C:\webserver\www\lizmap36\lizmap\plugins\formwidget/textarea_htmlbootstrap/"
time_htmlbootstrap="C:\webserver\www\lizmap36\lizmap\plugins\formwidget/time_htmlbootstrap/"
upload2_htmlbootstrap="C:\webserver\www\lizmap36\lizmap\plugins\formwidget/upload2_htmlbootstrap/"
upload_htmlbootstrap="C:\webserver\www\lizmap36\lizmap\plugins\formwidget/upload_htmlbootstrap/"
wikieditor_htmlbootstrap="C:\webserver\www\lizmap36\lizmap\plugins\formwidget/wikieditor_htmlbootstrap/"
[_pluginsPathList_htmlresponse]
debugbar="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\htmlresponse/debugbar/"
[_pluginsPathList_jforms]
html="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\jforms/html/"
htmllight="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\jforms/htmllight/"
[_pluginsPathList_kvdb]
db="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\kvdb/db/"
dba="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\kvdb/dba/"
file2="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\kvdb/file2/"
memcache="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\kvdb/memcache/"
redis_ext="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\kvdb/redis_ext/"
file="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix-plugins\kvdb/file/"
[_pluginsPathList_logger]
firebug="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\logger/firebug/"
legacysyslog="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\logger/legacysyslog/"
soapfile="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\logger/soapfile/"
[_pluginsPathList_profiles]
jdb="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\profiles/jdb/"
[_tplpluginsPathList_common]
0="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix-modules\jacl2\plugins\tpl/common/"
1="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix-modules\jacl\plugins\tpl/common/"
2="C:\webserver\www\lizmap36\lizmap\plugins\tpl/common/"
3="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\tpl/common/"
[_tplpluginsPathList_html]
0="C:\webserver\www\lizmap36\lizmap\plugins\tpl/html/"
1="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\tpl/html/"
[_tplpluginsPathList_ltx2pdf]
0="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\tpl/ltx2pdf/"
[_tplpluginsPathList_text]
0="C:\webserver\www\lizmap36\lizmap\plugins\tpl/text/"
1="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\tpl/text/"
[_tplpluginsPathList_xml]
0="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\plugins\tpl/xml/"
[_pluginsPathList_acl2]
db="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix-modules\jacl2db\plugins\acl2/db/"
dbcache="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix-modules\jacl2db\plugins\acl2/dbcache/"
[_pluginsPathList_acl]
db="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix-modules\jacldb\plugins\acl/db/"
[_autoload_class]
jAcl2="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix-modules\jacl2\classes/jAcl2.class.php"
jIAcl2Driver="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix-modules\jacl2\classes/jIAcl2Driver.iface.php"
jIAcl2Driver2="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix-modules\jacl2\classes/jIAcl2Driver2.iface.php"
jAcl2Authentication="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix-modules\jacl2\classes/jAcl2Authentication.class.php"
jAcl2JAuthAdapter="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix-modules\jacl2\classes/jAcl2JAuthAdapter.class.php"
jAcl2AuthAdapterInterface="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix-modules\jacl2\classes/jAcl2AuthAdapterInterface.iface.php"
lizmap="C:\webserver\www\lizmap36\lizmap\modules\lizmap\classes/lizmap.class.php"
lizmapLogItem="C:\webserver\www\lizmap36\lizmap\modules\lizmap\classes/lizmapLogItem.class.php"
lizmapLogConfig="C:\webserver\www\lizmap36\lizmap\modules\lizmap\classes/lizmapLogConfig.class.php"
qgisServer="C:\webserver\www\lizmap36\lizmap\modules\lizmap\classes/qgisServer.class.php"
lizmapProject="C:\webserver\www\lizmap36\lizmap\modules\lizmap\classes/lizmapProject.class.php"
lizmapRepository="C:\webserver\www\lizmap36\lizmap\modules\lizmap\classes/lizmapRepository.class.php"
lizmapTiler="C:\webserver\www\lizmap36\lizmap\modules\lizmap\classes/lizmapTiler.class.php"
lizmapWkt="C:\webserver\www\lizmap36\lizmap\modules\lizmap\classes/lizmapWkt.class.php"
qgisMapLayer="C:\webserver\www\lizmap36\lizmap\modules\lizmap\classes/qgisMapLayer.class.php"
qgisVectorLayerDatasource="C:\webserver\www\lizmap36\lizmap\modules\lizmap\classes/qgisVectorLayerDatasource.class.php"
qgisVectorLayer="C:\webserver\www\lizmap36\lizmap\modules\lizmap\classes/qgisVectorLayer.class.php"
qgisAttributeEditorElement="C:\webserver\www\lizmap36\lizmap\modules\lizmap\classes/qgisAttributeEditorElement.class.php"
qgisLayerDbFieldsInfo="C:\webserver\www\lizmap36\lizmap\modules\lizmap\classes/qgisLayerDbFieldsInfo.class.php"
lizmapServices="C:\webserver\www\lizmap36\lizmap\modules\lizmap\classes/lizmapServices.class.php"
qgisExpressionUtils="C:\webserver\www\lizmap36\lizmap\modules\lizmap\classes/qgisExpressionUtils.class.php"
lizmapProxy="C:\webserver\www\lizmap36\lizmap\modules\lizmap\classes/lizmapProxy.class.php"
lizmapOGCRequest="C:\webserver\www\lizmap36\lizmap\modules\lizmap\classes/lizmapOGCRequest.class.php"
lizmapMainViewItem="C:\webserver\www\lizmap36\lizmap\modules\view\classes/lizmapMainViewItem.class.php"
lizmapMapDockItem="C:\webserver\www\lizmap36\lizmap\modules\view\classes/lizmapMapDockItem.class.php"
[_autoload_namespace]
[_autoload_classpattern]
regexp[]="/^jAcl2Db/"
path[]="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix-modules\jacl2db\classes/|.class.php"
[_autoload_includepathmap]
[_autoload_includepath]
[_autoload_namespacepathmap]
Jelix\JelixModule="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib/jelix/core-modules/jelix\./|.php"
Jelix\JCommunity="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jcommunity-module\modules\jcommunity\lib|.php"
Jelix\Acl2Db="C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix-modules\jacl2db\./|.php"
Lizmap="C:\webserver\www\lizmap36\lizmap\modules\lizmap\lib|.php"
[_autoload_autoloader]
[compiled_webassets_common]
dependencies_order[]=jquery
dependencies_order[]=jquery_ui
dependencies_order[]=jforms_html
dependencies_order[]=jforms_html_light
dependencies_order[]=jforms_datepicker_default
dependencies_order[]=jforms_datetimepicker_default
dependencies_order[]=jforms_htmleditor_default
dependencies_order[]=jforms_htmleditor_ckdefault
dependencies_order[]=jforms_htmleditor_ckfull
dependencies_order[]=jforms_htmleditor_ckbasic
dependencies_order[]=jforms_wikieditor_default
dependencies_order[]=jforms_imageupload
dependencies_order[]=jforms_autocomplete
dependencies_order[]=jforms_autocompleteajax
dependencies_order[]=bootstrap
dependencies_order[]=datatables
dependencies_order[]=jforms_htmleditor_ckfullandmedia
dependencies_order[]=map
dependencies_order[]=maptheme
dependencies_order[]=normal
dependencies_order[]=view
dependencies_order[]=embed
dependencies_order[]=jauthdb_admin
dependencies_order[]=jacl2_admin
webassets_jquery.js[]="k>assets/js/jquery/jquery-3.5.1.min.js?_r=231007075320>"
webassets_jquery.js[]="k>assets/js/jquery/jquery-migrate-3.3.1.min.js?_r=231007075320>"
webassets_jquery_ui.deps[]=jquery
webassets_jquery_ui.js[]="u>/lizmap36/lizmap/www/assets/jelix/jquery/ui/jquery-ui.min.js?_r=231007075320>"
webassets_jquery_ui.css[]="u>/lizmap36/lizmap/www/assets/jelix/jquery/ui/jquery-ui.min.css?_r=231007075320>"
webassets_jforms_html.deps[]=jquery
webassets_jforms_html.js[]="u>/lizmap36/lizmap/www/assets/jelix/js/jforms_jquery.js?_r=231007075320>"
webassets_jforms_html.css[]="u>/lizmap36/lizmap/www/assets/jelix/design/jform.css?_r=231007075320>"
webassets_jforms_html_light.js[]="u>/lizmap36/lizmap/www/assets/jelix/js/jforms_light.js?_r=231007075320>"
webassets_jforms_html_light.css[]="u>/lizmap36/lizmap/www/assets/jelix/design/jform.css?_r=231007075320>"
webassets_jforms_datepicker_default.deps[]=jquery_ui
webassets_jforms_datepicker_default.deps[]=jquery
webassets_jforms_datepicker_default.js[]="l>/lizmap36/lizmap/www/assets/jelix/jquery/ui/i18n/datepicker-$lang.js?_r=231007075320>"
webassets_jforms_datepicker_default.js[]="l>/lizmap36/lizmap/www/assets/jelix/js/jforms/datepickers/default/ui.$lang.js?_r=231007075320>"
webassets_jforms_datepicker_default.js[]="u>/lizmap36/lizmap/www/assets/jelix/js/jforms/datepickers/default/init.js?_r=231007075320>"
webassets_jforms_datetimepicker_default.deps[]=jforms_datepicker_default
webassets_jforms_datetimepicker_default.deps[]=jquery_ui
webassets_jforms_datetimepicker_default.deps[]=jquery
webassets_jforms_datetimepicker_default.js[]="u>/lizmap36/lizmap/www/assets/jelix/js/jforms/datetimepickers/default/init.js?_r=231007075320>"
webassets_jforms_datetimepicker_default.js[]="u>/lizmap36/lizmap/www/assets/jelix/jquery/jquery-ui-timepicker-addon.js?_r=231007075320>"
webassets_jforms_datetimepicker_default.css[]="u>/lizmap36/lizmap/www/assets/jelix/jquery/jquery-ui-timepicker-addon.css?_r=231007075320>"
webassets_jforms_htmleditor_default.js[]="u>/lizmap36/lizmap/www/assets/jelix/ckeditor5/ckeditor.js?_r=231007075320>"
webassets_jforms_htmleditor_default.js[]="l>/lizmap36/lizmap/www/assets/jelix/ckeditor5/translations/$lang.js?_r=231007075320>"
webassets_jforms_htmleditor_default.js[]="k>assets/js/ckeditor5/ckeditor_lizmap.js?_r=231007075320>"
webassets_jforms_htmleditor_ckdefault.js[]="u>/lizmap36/lizmap/www/assets/jelix/ckeditor5/ckeditor.js?_r=231007075320>"
webassets_jforms_htmleditor_ckdefault.js[]="l>/lizmap36/lizmap/www/assets/jelix/ckeditor5/translations/$lang.js?_r=231007075320>"
webassets_jforms_htmleditor_ckdefault.js[]="k>assets/js/ckeditor5/ckeditor_lizmap.js?_r=231007075320>"
webassets_jforms_htmleditor_ckfull.js[]="u>/lizmap36/lizmap/www/assets/jelix/ckeditor5/ckeditor.js?_r=231007075320>"
webassets_jforms_htmleditor_ckfull.js[]="l>/lizmap36/lizmap/www/assets/jelix/ckeditor5/translations/$lang.js?_r=231007075320>"
webassets_jforms_htmleditor_ckfull.js[]="u>/lizmap36/lizmap/www/assets/jelix/js/jforms/htmleditors/ckeditor_ckfull.js?_r=231007075320>"
webassets_jforms_htmleditor_ckbasic.js[]="u>/lizmap36/lizmap/www/assets/jelix/ckeditor5/ckeditor.js?_r=231007075320>"
webassets_jforms_htmleditor_ckbasic.js[]="l>/lizmap36/lizmap/www/assets/jelix/ckeditor5/translations/$lang.js?_r=231007075320>"
webassets_jforms_htmleditor_ckbasic.js[]="u>/lizmap36/lizmap/www/assets/jelix/js/jforms/htmleditors/ckeditor_ckbasic.js?_r=231007075320>"
webassets_jforms_wikieditor_default.deps[]=jquery
webassets_jforms_wikieditor_default.js[]="u>/lizmap36/lizmap/www/assets/jelix/markitup/jquery.markitup.js?_r=231007075320>"
webassets_jforms_wikieditor_default.js[]="l>/lizmap36/lizmap/www/assets/jelix/markitup/sets/wr3/$locale.js?_r=231007075320>"
webassets_jforms_wikieditor_default.css[]="u>/lizmap36/lizmap/www/assets/jelix/markitup/skins/simple/style.css?_r=231007075320>"
webassets_jforms_wikieditor_default.css[]="u>/lizmap36/lizmap/www/assets/jelix/markitup/sets/wr3/style.css?_r=231007075320>"
webassets_jforms_imageupload.deps[]=jquery_ui
webassets_jforms_imageupload.deps[]=jquery
webassets_jforms_imageupload.js[]="u>/lizmap36/lizmap/www/assets/jelix/js/cropper.min.js?_r=231007075320>"
webassets_jforms_imageupload.js[]="u>/lizmap36/lizmap/www/assets/jelix/js/jforms/choice.js?_r=231007075320>"
webassets_jforms_imageupload.js[]="u>/lizmap36/lizmap/www/assets/jelix/js/jforms/imageSelector.js?_r=231007075320>"
webassets_jforms_imageupload.css[]="u>/lizmap36/lizmap/www/assets/jelix/js/cropper.min.css?_r=231007075320>"
webassets_jforms_autocomplete.deps[]=jquery_ui
webassets_jforms_autocomplete.deps[]=jquery
webassets_jforms_autocomplete.js[]="u>/lizmap36/lizmap/www/assets/jelix/js/jforms/jAutocomplete.jqueryui.js?_r=231007075320>"
webassets_jforms_autocompleteajax.deps[]=jquery_ui
webassets_jforms_autocompleteajax.deps[]=jquery
webassets_jforms_autocompleteajax.js[]="u>/lizmap36/lizmap/www/assets/jelix/js/jforms/jAutocompleteAjax.jqueryui.js?_r=231007075320>"
webassets_datatables.deps[]=bootstrap
webassets_datatables.deps[]=jquery
webassets_datatables.js[]="k>assets/js/jquery.dataTables.min.js?_r=231007075320>"
webassets_datatables.js[]="k>assets/js/dataTables.bootstrap.min.js?_r=231007075320>"
webassets_datatables.js[]="l>/lizmap36/lizmap/www/assets/jelix/datatables/i18n/$locale.js?_r=231007075320>"
webassets_datatables.css[]="k>assets/css/jquery.dataTables.min.css?_r=231007075320>"
webassets_datatables.css[]="k>assets/css/dataTables.bootstrap.min.css?_r=231007075320>"
webassets_jforms_htmleditor_ckfullandmedia.js[]="u>/lizmap36/lizmap/www/assets/jelix/ckeditor5/ckeditor.js?_r=231007075320>"
webassets_jforms_htmleditor_ckfullandmedia.js[]="l>/lizmap36/lizmap/www/assets/jelix/ckeditor5/translations/$lang.js?_r=231007075320>"
webassets_jforms_htmleditor_ckfullandmedia.js[]="k>assets/js/ckeditor5/ckeditor_ckfullandmedia.js?_r=231007075320>"
webassets_bootstrap.deps[]=jquery
webassets_bootstrap.js[]="k>assets/js/bootstrap.min.js?_r=231007075320>"
webassets_bootstrap.css[]="k>assets/css/bootstrap.min.css?_r=231007075320>"
webassets_bootstrap.css[]="k>assets/css/bootstrap-responsive.min.css?_r=231007075320>"
webassets_map.deps[]=bootstrap
webassets_map.deps[]=jquery
webassets_map.js[]="k>assets/js/OpenLayers-2.13/OpenLayers.js?_r=231007075320>"
webassets_map.js[]="k>assets/js/Proj4js/proj4js.min.js?_r=231007075320>"
webassets_map.js[]="k>assets/js/jquery.combobox.js?_r=231007075320>"
webassets_map.js[]="k>assets/js/TreeTable/javascripts/jquery.treeTable.js?_r=231007075320>"
webassets_map.js[]="k>assets/js/map.js?_r=231007075320>"
webassets_map.js[]="k>assets/js/lizmap.js?_r=231007075320>"
webassets_map.css[]="k>assets/js/TreeTable/stylesheets/jquery.treeTable.css?_r=231007075320>"
webassets_map.css[]="k>assets/js/OpenLayers-2.13/theme/default/style.css?_r=231007075320>"
webassets_map.css[]="k>assets/css/ol.css?_r=231007075320>"
webassets_map.css[]="k>assets/css/main.css?_r=231007075320>"
webassets_map.css[]="k>assets/css/map.css?_r=231007075320>"
webassets_map.css[]="k>assets/css/media.css?_r=231007075320>"
webassets_maptheme.css[]="t>$theme/css/main.css?_r=231007075320>"
webassets_maptheme.css[]="t>$theme/css/map.css?_r=231007075320>"
webassets_maptheme.css[]="t>$theme/css/media.css?_r=231007075320>"
webassets_normal.css[]="k>assets/css/main.css?_r=231007075320>"
webassets_normal.css[]="k>assets/css/view.css?_r=231007075320>"
webassets_normal.css[]="k>assets/css/media.css?_r=231007075320>"
webassets_view.js[]="k>assets/js/view.js?_r=231007075320>"
webassets_embed.css[]="k>assets/css/embed.css?_r=231007075320>"
webassets_embed.css[]="t>$theme/css/embed.css?_r=231007075320>"
webassets_jauthdb_admin.deps[]=jquery_ui
webassets_jauthdb_admin.deps[]=jquery
webassets_jauthdb_admin.js[]="u>/lizmap36/lizmap/www/assets/jelix/js/authdb_admin.js?_r=231007075320>"
webassets_jacl2_admin.deps[]=jquery_ui
webassets_jacl2_admin.deps[]=jquery
webassets_jacl2_admin.js[]="u>/lizmap36/lizmap/www/assets/jelix/js/jacl2db_admin.js?_r=231007075320>"
webassets_jacl2_admin.css[]="u>/lizmap36/lizmap/www/assets/jelix/design/jacl2.css?_r=231007075320>"
webassets_jacl2_admin.css[]="u>/lizmap36/lizmap/www/assets/jelix/design/records_list.css?_r=231007075320>"
